[GENERAL]

# The assignment key you have to press when assigning hotkeys in the favorites menu.
# Requires a DirectInput scan code of the key you want to use.See the included scancodes.txt file for a list of buttons.
# Example: iAssignmentKey = 45 is the the 'X' button.
# Default value is 29, which is the left control key.
iAssignmentKey = 29

# If enabled, assigning a button that is already in use keeps the old hotkey as well.
# Pressing the button then equips or unequips all of its items together.
# Default is false (disabled, the old hotkey is replaced)
bAllowDuplicates = false


[WHITELIST]

# Enable or disable the button whitelist. If enabled, only whitelisted buttons can be set as a hotkey.
# You don't have to hold down the assignment key to assign these hotkeys.
# Default is true (enabled)
bUseWhitelist = true

# The list of buttons that can be set as hotkey.
# Requires a DirectInput scan code of the key you want to use.See the included scancodes.txt file for a list of buttons.
# Separate the entries with commas(, ) do not use spaces or any other characters!
# Example: sWhitelist = 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 (these are the numeric buttons from 0 to 9)
sWhitelist = 2,3,4,5,6,7,8,9,10,11

# If enabled, the assignment key + hotkey combination can no longer assign a hotkey outside of the whitelist.
# Default is false (disabled)
bEnforceWhitelist = false
