#ifndef MOREHOTKEYS_VERSION_INCLUDED
#define MOREHOTKEYS_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define MOREHOTKEYS_VERSION_MAJOR		1
#define MOREHOTKEYS_VERSION_MINOR		1
#define MOREHOTKEYS_VERSION_PATCH		0
#define MOREHOTKEYS_VERSION_BETA		0
#define MOREHOTKEYS_VERSION_VERSTRING	MAKE_STR(MOREHOTKEYS_VERSION_MAJOR) "." MAKE_STR(MOREHOTKEYS_VERSION_MINOR) "." MAKE_STR(MOREHOTKEYS_VERSION_PATCH) "." MAKE_STR(MOREHOTKEYS_VERSION_BETA)

#endif
